version: "3.8"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: netskope
    ports:
      - 8080:3306
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
  app:
    image: netskope-app
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3000:3000
